services:
  - type: web
    name: papertrail
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn papertrail.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: papertrail-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.4


databases:
  - name: papertrail-db
    databaseName: papertrail
    plan: free
    postgresMajorVersion: 14
